const range=(key,label,min,max,step,value,unit='')=>`<label class="lab-control">${label} <output data-out="${key}">${value} ${unit}</output><input data-param="${key}" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const select=(key,label,options)=>`<label class="lab-control">${label}<select data-param="${key}" aria-label="${label}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
const setups={
 nongrey:{title:'不透明度与连续谱形成深度',controls:range('r','不透明度比 r',0.25,4,0.05,1)+range('T','背景温度参数',5000,12000,100,8000,'K')+range('wave','考察波长 / nm',300,800,10,360),note:'平面平行、LTE、真吸收；固定灰背景 T⁴=(3/4)T₀⁴(τR+2/3)，r=κλ/κR 沿深度不变。用 τλ=2/3 的 Eddington–Barbier 估计出射通量；未重新求辐射平衡，T₀ 只是背景参数。实线为温度，虚线标形成深度；非观测谱或自洽非灰大气。',prompt:'增大 r，观察对应的 τR、局部温度和同波长通量比；再改变波长，比较同样的温差对 Planck 函数的影响。'},
 rosseland:{title:'两个波段的 Rosseland 平均',controls:range('a','波段 A 不透明度 / κ₀',0.1,10,0.1,1)+range('b','波段 B 不透明度 / κ₀',0.1,10,0.1,10)+range('w','波段 A 温度导数权重 w',0.05,0.95,0.05,0.5),note:'光学厚扩散近似；两个波段各自具有恒定质量不透明度。w 和 1−w 是归一化的 ∂Bλ/∂T 积分权重，由滑块独立指定；κ₀ 是共同正参考值。条形长度按数值计算，非真实恒星不透明度表。',prompt:'固定等权重，比较 1 与 10 的调和平均和算术平均；降低较透明波段的不透明度，观察它对平均值和输运份额的作用。'},
 scaleheight:{title:'等温大气的压强标高',controls:range('T','气体温度',4000,12000,100,6000,'K')+range('g','重力加速度 / m s⁻²',50,500,10,270)+range('mu','平均粒子质量 / 氢原子质量',0.6,1.3,0.1,1.3),note:'等温、平面平行、理想气体；g 与 μ 恒定，仅气体压强提供支撑。向外高度 z 从共同基底算起，P/P₀=exp(−z/H)，H=kT/(μmH g)。实线为当前模型，虚线固定 T=6000 K、g=270 m s⁻²、μ=1.3；非实测大气。',prompt:'分别改变 T、g、μ，比较标高 H 和相同几何高度处的压强；读出 z=H 时保留的压强比例。'},
 pressure:{title:'同一光学深度处的压强与重力',controls:range('g','重力加速度 / m s⁻²',50,400,10,100)+range('n','不透明度的压强指数 n',0,2,1,1)+range('tau','考察光学深度',0.1,2,0.1,1),note:'平面平行静力模型，κR=κ₀(P/P₀)ⁿ，κ₀=0.01 m² kg⁻¹、P₀=10⁴ Pa；表面 P=0，忽略湍流和辐射支撑。n=0、1、2 是假定幂律；实线为当前 g，虚线为 g=100 m s⁻²，圆点为所选深度。n>0 的零压强边界只用作解析极限。',prompt:'固定 τR 和 n，将 g 从 100 改为 400，观察压强比；再比较 n=0、1、2，解释不透明度反馈怎样改变重力依赖。'},
 limb:{title:'出射方向与源函数深度',controls:range('mu','方向余弦 μ',0.05,1,0.05,1)+range('b','源函数斜率 b / Iᵣ',0,2,0.1,1)+range('q','二次项系数 q / Iᵣ',0,0.5,0.05,0),note:'半无限、平面平行、无外部照射；S/Iᵣ=0.4+bτ+qτ²，各系数及 τ 无量纲。实线为积分得到的 I(0,μ)/Iᵣ=0.4+bμ+2qμ²，虚线为 S(τ=μ)/Iᵣ。这是解析教学模型，不是太阳观测拟合。μ→0 只表示平面平行模型的极限。',prompt:'改变 μ 比较中心和近边缘的强度；增大二次项，观察出射强度与单层源函数之间的差别。'},
 grey:{title:'灰大气的温度分层',controls:range('tau','向内光学深度 τ',0,5,0.05,0.65)+range('T','有效温度',4000,10000,100,6000,'K'),note:'平面平行、灰、LTE 热发射、辐射平衡；采用 Eddington 闭合 K=J/3 和 J(0)=2H。曲线按 T⁴=(3/4)T<sub>eff</sub>⁴(τ+2/3) 计算，非太阳实测温度。实线：当前有效温度；虚线：6000 K 参考模型；圆点：当前深度。',prompt:'改变深度观察局部温度，比较 τ=0 与 τ=2/3；再改变有效温度，比较维持恒定通量所需的温度分层。'},
 edges:{title:'氢的束缚—自由吸收阈值',controls:range('n','氢原子初始主量子数 n',1,3,1,2)+range('wave','入射光波长 λ / nm',50,1000,5,400),note:'孤立氢原子，能级电离能近似 13.6/n² eV；忽略细结构与受激过程。光子能量用 hc/λ 计算。线段只标能量与阈值，不表示吸收截面或恒星光谱。',prompt:'选择初始能级并改变波长，观察光子是否有足够能量使电子电离；区分能量允许与实际吸收强弱。'},
 projection:{title:'比强度与接收面积的投影',controls:range('theta','光线与表面法线夹角 θ',0,85,1,30,'°')+range('area','接收面积 / 参考面积',0.5,2,0.1,1),note:'固定比强度、微小立体角、波长带宽与接收时间。图为二维截面，面板长度表示面积比例；光线用平行箭头示意，不表示单个光子。归一化接收能量 E/E₀=(A/A₀)cosθ。',prompt:'倾斜接收面，观察垂直于光线的投影和接收能量；再扩大面积，区分能量与比强度。'},
 transfer:{title:'穿过气层后，光来自哪里',controls:range('tau','沿光路的光学深度 τ',0,8,0.05,1)+range('I0','入射比强度 I₀ / Iᵣ',0,2,0.05,1)+range('S','源函数 S / Iᵣ',0,2,0.05,0.4),note:'固定波长；稳态、无散射，源函数沿路恒定。Iᵣ 是固定正参考比强度；所有纵轴量除以 Iᵣ，τ 无量纲。实线为总强度，长虚线为透射背景，点线为气层发射；横虚线标出 S。',prompt:'先固定 I₀ 和 S 增大 τ，比较背景与气层的贡献；再让 S 跨过 I₀，观察总强度变化方向。'},
 lineformation:{title:'同一条谱线：吸收、发射与饱和',controls:range('I0','背景 I₀ / Iᵣ',0,2,0.05,1)+range('S','源函数 S / Iᵣ',0,2,0.05,0.4)+range('lineDepth','线心附加光学深度 τₗ',0,12,0.1,2)+range('continuum','连续谱光学深度 τ꜀',0,8,0.05,0.1),note:'原创窄带教学模型：x=(λ−λ₀)/Δλ，τ(x)=τ꜀+τₗ exp(−x²/2)，Δλ 为固定宽度单位。I₀、S 在此窄带及沿气层均恒定，无散射；非实测谱，不对应具体原子。固定 Iᵣ 归一化；虚线为去掉谱线不透明度后的连续谱。',prompt:'保持光学深度不变，改变背景或源函数，使谱线由凹陷变为凸起；再比较只增大线心厚度和让连续谱也变厚的结果。'},
 stratification:{title:'光学厚大气中的温度梯度与谱线',controls:range('gradient','向内源函数增量 g',-1.5,1.5,0.1,1)+range('opacity','线心 / 连续谱吸收系数 r',1,12,0.5,5),note:'原创分层数值模型，无散射、垂直射线。以连续谱光深 z 为向内坐标，0≤z≤8；S/Iᵣ=1+g(z/8−1/2)，底部 I/Iᵣ=1+g/2。240 层逐层精确传播，窄带源函数无波长差异。线心光深为 rz；非真实大气合成谱。',prompt:'将 g 从正调到负，比较连续谱和线心出射强度。再增大 r，观察线心更偏重浅层时，谱线怎样改变。'},
 brightness:{title:'距离、光度与接收通量',controls:range('d','距离',10,100,1,10,'pc')+range('L','光度倍数',0.1,10,0.1,1),note:'以光度 L₀、距离 10 pc 的恒星为参考，忽略消光；图中光点大小是符号，通量柱才表示数值。',prompt:'分别改变距离和光度，比较接收通量与星等差。'},
 color:{title:'黑体温度与波段通量比',controls:range('T','黑体温度',3000,20000,100,6000,'K'),note:'教学近似：B、V 是 440、550 nm 的等宽窄窗，10,000 K 黑体定义色指数零点。不是标准 Johnson B−V 标定；曲线按各自峰值归一化。',prompt:'改变黑体温度，比较两个窄波段的通量比和色指数。'},
 airmass:{title:'大气消光与星等改正',controls:range('k','消光系数',0,0.6,0.01,0.2,'mag/airmass')+range('X','大气质量 X',1,3,0.1,1),note:'m(X)=m₀+kX，固定大气外星等 m₀=8；均匀稳定大气、固定波段的简化模型，忽略颜色项。X=0 是外推，不是地面可直接观测的位置。',prompt:'改变大气质量和消光系数，比较观测星等与大气外截距。'},
 cmd:{title:'颜色—星等图中的距离影响',controls:select('group','恒星示意族群',[['main','主序：蓝端亮，红端暗'],['giant','红巨星：偏红而亮'],['dwarf','白矮星：偏蓝而暗']])+range('d','共同距离',10,100,1,10,'pc')+select('axis','纵轴选择',[['M','绝对 V 星等 Mᵥ'],['m','视 V 星等 mᵥ']]),note:'点为人工构造的族群示意，无观测数据或演化轨迹含义；忽略消光，各点距离相同。横轴为示意 B−V，纵轴星等向上减小。',prompt:'选择恒星族群和星等纵轴，观察距离改变时的位置变化。'},
 hydrogen:{title:'氢的激发与电离',controls:range('T','气体温度',4000,25000,100,9000,'K')+range('ne','电子密度 log₁₀(nₑ / m⁻³)',18,22,0.1,20),note:'LTE 理想氢示意：两式一致截断到 n=1、2，曲线各自按峰归一化。外加电子密度的参数扫描，不是固定总氢密度下的自洽大气；n=2 占比不是等值宽度。',prompt:'改变温度或电子密度，观察中性比例、激发比例及其乘积。'},
 spectra:{title:'光谱型与吸收线特征',controls:range('type','光谱型序列位置',0,6,1,2),note:'吸收凹陷是为比较特征而构造的示意，不是实测或大气模型合成谱；深度不用于丰度反演，线宽也不编码光度级。',prompt:'沿 O 到 M 调整谱型，比较巴耳末线、氦线和冷端分子带。'},
 blackbody:{title:'黑体辐射谱与温度',controls:range('T','黑体温度',3000,15000,100,6000,'K')+select('density','谱密度表示',[['lambda','Bλ：每单位波长'],['nu','Bν：每单位频率']])+select('scale','纵轴尺度',[['absolute','固定对数尺度：比较强度'],['normalized','归一化：只比较谱形']]),note:'实线为当前温度，虚线固定 6000 K。固定对数尺度以该表示下 6000 K 的峰为单位，低于其 10⁻⁴ 的部分贴近图底；截取有限横轴窗口，读出的总流量使用 σT⁴ 全谱积分。',prompt:'改变温度并切换谱密度表示，比较谱峰、固定波长处强度及总表面通量。'},
 temperature:{title:'半径、有效温度与光度',controls:range('T','有效温度',3000,12000,100,6000,'K')+range('R','半径',0.5,5,0.1,1,'R☉'),note:'用 L/L☉=(R/R☉)²(T<sub>eff</sub>/5800 K)⁴，5800 K 仅作本活动的参考归一化温度；表面色彩是示意，不是色度计算。',prompt:'分别改变半径与有效温度，比较表面通量和总光度。'}
};
export const activityTypes=Object.keys(setups);
const notation=s=>s.replace(/([κτ])([Rλ])/g,'$1<sub>$2</sub>').replace(/Bλ/g,'B<sub>λ</sub>');
export function explorerHTML(a){const s=setups[a.type];if(!s)throw Error('未知活动');return `<div class="activity explorer" id="${a.id}" data-explorer="${a.type}"><div class="activity-head"><button class="feedback-link" data-feedback="${a.id}" data-label="${s.title}" type="button">反馈</button></div><h3>${s.title}</h3><p class="prediction">${notation(s.prompt)}</p><div class="lab-layout"><div class="lab-plot">${a.type==='transfer'?'<div class="rt-legend"><span>总强度</span><span>透射背景</span><span>气层发射</span></div>':''}<svg viewBox="0 0 700 360" role="img" aria-label="${s.title}的交互图表"></svg><div class="lab-result" aria-live="polite"></div></div><div class="lab-controls">${s.controls}</div></div><p class="caption">${notation(s.note)}</p></div>`;}
