const range=(key,label,min,max,step,value,unit='')=>`<label class="lab-control">${label} <output data-out="${key}">${value} ${unit}</output><input data-param="${key}" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const select=(key,label,options)=>`<label class="lab-control">${label}<select data-param="${key}" aria-label="${label}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
const setups={
 brightness:{title:'把同一颗星推远',controls:range('d','距离',10,100,1,10,'pc')+range('L','光度倍数',0.1,10,0.1,1),note:'以光度 L₀、距离 10 pc 的恒星为参考，忽略消光；图中光点大小是符号，光流柱才表示数值。',prompt:'先预测：距离翻倍，需要把光度变成多少，才能恢复原来的视亮度？'},
 color:{title:'同一束星光，经过两扇窗口',controls:range('T','黑体温度',3000,20000,100,6000,'K'),note:'教学近似：B、V 是 440、550 nm 的等宽窄窗，10,000 K 黑体定义色指数零点。不是标准 Johnson B−V 标定；曲线按各自峰值归一化。',prompt:'把温度调高：蓝窗相对绿窗的光流如何变化？负色指数意味着什么？'},
 airmass:{title:'用多次观测，把大气影响外推掉',controls:range('k','消光系数',0,0.6,0.01,0.2,'mag/airmass')+range('X','大气质量 X',1,3,0.1,1),note:'m(X)=m₀+kX，固定大气外星等 m₀=8；均匀稳定大气、固定波段的简化模型，忽略颜色项。X=0 是外推，不是地面可直接观测的位置。',prompt:'沿直线回到 X=0，读数为什么才是大气外星等？'},
 cmd:{title:'一张图上，分开距离与恒星本身',controls:select('group','恒星示意族群',[['main','主序：蓝端亮，红端暗'],['giant','红巨星：偏红而亮'],['dwarf','白矮星：偏蓝而暗']])+range('d','共同距离',10,100,1,10,'pc')+select('axis','纵轴选择',[['M','绝对 V 星等 Mᵥ'],['m','视 V 星等 mᵥ']]),note:'点为人工构造的族群示意，无观测数据或演化轨迹含义；忽略消光，各点距离相同。横轴为示意 B−V，纵轴星等向上减小。',prompt:'先换族群，再只改距离。哪种纵轴能让位置不随距离改变？'},
 hydrogen:{title:'两道门：先留住电子，再把它激发',controls:range('T','气体温度',4000,25000,100,9000,'K')+range('ne','电子密度 log₁₀(nₑ / m⁻³)',18,22,0.1,20),note:'LTE 理想氢示意：两式一致截断到 n=1、2，曲线各自按峰归一化。外加电子密度的参数扫描，不是固定总氢密度下的自洽大气；n=2 占比不是等值宽度。',prompt:'升温一面帮助激发，一面促进电离。n=2 占全部氢核的比例，会一直上升吗？'},
 spectra:{title:'沿光谱序列寻找“谁最显眼”',controls:range('type','光谱型序列位置',0,6,1,2),note:'吸收凹陷是为比较特征而构造的示意，不是实测或大气模型合成谱；深度不用于丰度反演，线宽也不编码光度级。',prompt:'从 O 移到 M：巴耳末线是否一直增强？先看特征，再判断温度方向。'},
 blackbody:{title:'拖动温度，看峰移动、面积增长',controls:range('T','黑体温度',3000,15000,100,6000,'K')+select('density','谱密度表示',[['lambda','Bλ：每单位波长'],['nu','Bν：每单位频率']])+select('scale','纵轴尺度',[['absolute','固定对数尺度：比较强度'],['normalized','归一化：只比较谱形']]),note:'实线为当前温度，虚线固定 6000 K。固定对数尺度以该表示下 6000 K 的峰为单位，低于其 10⁻⁴ 的部分贴近图底；截取有限横轴窗口，读出的总流量使用 σT⁴ 全谱积分。',prompt:'把 6000 K 调到 12,000 K：峰在哪？总流量增加几倍？再切换谱密度，看峰能否简单互换。'},
 temperature:{title:'半径和温度，各自怎样改变光度？',controls:range('T','有效温度',3000,12000,100,6000,'K')+range('R','半径',0.5,5,0.1,1,'R☉'),note:'用 L/L☉=(R/R☉)²(T_eff/5800 K)⁴，5800 K 仅作本活动的参考归一化温度；表面色彩是示意，不是色度计算。',prompt:'固定温度，把半径加倍。再固定半径，把温度加倍。哪一种使光度增长更多？'}
};
export const activityTypes=Object.keys(setups);
export function explorerHTML(a){const s=setups[a.type];if(!s)throw Error('未知活动');return `<div class="activity explorer" id="${a.id}" data-explorer="${a.type}"><div class="activity-head"><button class="feedback-link" data-feedback="${a.id}" data-label="${s.title}" type="button">这里有疑问 ↗</button></div><h3>${s.title}</h3><p class="prediction">${s.prompt}</p><div class="lab-layout"><div class="lab-plot"><svg viewBox="0 0 700 360" role="img" aria-label="${s.title}的交互图表"></svg><div class="lab-result" aria-live="polite"></div></div><div class="lab-controls">${s.controls}</div></div><p class="caption">${s.note}</p></div>`;}
